version: "3.7"
services:
    nextjs-site:
        build:
            context: .
            target: develop
            # target: deploy
        container_name: nextjs-site
        ports:
            - 3000:3000
            # - 80:3000
        volumes:
            - ./app/components:/app/components
            - ./app/data:/app/data
            - ./app/icomoon:/app/icomoon
            - ./app/pages:/app/pages
            - ./app/public:/app/public
            - ./app/styles:/app/styles